import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/landmark.dart';

final landmarkRepositoryProvider = Provider((ref) => LandmarkRepository());

class LandmarkRepository {
  Future<List<Landmark>> getLandmarks(String campusId) async {
    await Future.delayed(const Duration(milliseconds: 600)); // Simulate network
    final now = DateTime.now();

    // Comprehensive mock data for major Kenyan campuses
    switch (campusId) {
      case 'uon_main':
        return [
          Landmark(
            id: 'uon_lib_1',
            campusId: 'uon_main',
            name: 'Jomo Kenyatta Memorial Library',
            category: LandmarkCategory.academic,
            description: 'The iconic main library of the University of Nairobi, housing millions of volumes and providing extensive study spaces.',
            latitude: -1.2801,
            longitude: 36.8163,
            openingHours: 'Mon-Fri: 8:00 AM - 10:00 PM\nSat: 8:00 AM - 5:00 PM',
            phone: '+254 20 4910000',
            website: 'https://library.uonbi.ac.ke',
            isAccessible: true,
            photos: ['https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=1000'],
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_admin_1',
            campusId: 'uon_main',
            name: 'UoN Towers',
            category: LandmarkCategory.administration,
            description: 'State-of-the-art skyscraper housing the Vice Chancellor\'s office and key administrative departments.',
            latitude: -1.2805,
            longitude: 36.8168,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_food_1',
            campusId: 'uon_main',
            name: 'Main Campus Mess',
            category: LandmarkCategory.food,
            description: 'Central dining facility offering balanced meals at student-friendly prices.',
            latitude: -1.2795,
            longitude: 36.8158,
            openingHours: 'Daily: 7:00 AM - 8:30 PM',
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_gate_1',
            campusId: 'uon_main',
            name: 'Main Gate',
            category: LandmarkCategory.transport,
            description: 'The primary entry and exit point located along University Way.',
            latitude: -1.2810,
            longitude: 36.8170,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_academic_2',
            campusId: 'uon_main',
            name: 'Hyslop Building',
            category: LandmarkCategory.academic,
            description: 'Houses the Faculty of Arts and various lecture halls.',
            latitude: -1.2798,
            longitude: 36.8165,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_academic_3',
            campusId: 'uon_main',
            name: 'Education Building',
            category: LandmarkCategory.academic,
            description: 'Primary facility for the School of Education.',
            latitude: -1.2808,
            longitude: 36.8155,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_health_1',
            campusId: 'uon_main',
            name: 'University Health Services',
            category: LandmarkCategory.health,
            description: 'Comprehensive health facility for students and staff.',
            latitude: -1.2785,
            longitude: 36.8160,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_recreation_1',
            campusId: 'uon_main',
            name: 'University Sports Ground',
            category: LandmarkCategory.recreation,
            description: 'Main outdoor sports facility for football, rugby, and athletics.',
            latitude: -1.2775,
            longitude: 36.8175,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'uon_security_1',
            campusId: 'uon_main',
            name: 'Security Headquarters',
            category: LandmarkCategory.security,
            description: 'Central command for campus security operations.',
            latitude: -1.2815,
            longitude: 36.8160,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
        ];

      case 'ku_main':
        return [
          Landmark(
            id: 'ku_lib_1',
            campusId: 'ku_main',
            name: 'Post-Modern Library',
            category: LandmarkCategory.academic,
            description: 'Kenyatta University\'s expansive post-modern library, one of the largest in the region.',
            latitude: -1.1813,
            longitude: 36.9312,
            openingHours: 'Daily: 8:00 AM - 10:00 PM',
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'ku_admin_1',
            campusId: 'ku_main',
            name: 'KU Admin Block',
            category: LandmarkCategory.administration,
            description: 'The central hub for KU administrative services.',
            latitude: -1.1820,
            longitude: 36.9320,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'ku_gate_1',
            campusId: 'ku_main',
            name: 'Main Gate',
            category: LandmarkCategory.transport,
            description: 'The main entrance to Kenyatta University along the Thika Superhighway.',
            latitude: -1.1850,
            longitude: 36.9350,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'ku_health_1',
            campusId: 'ku_main',
            name: 'KU Health Unit',
            category: LandmarkCategory.health,
            description: 'Provides healthcare services to the KU community.',
            latitude: -1.1800,
            longitude: 36.9300,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'ku_recreation_1',
            campusId: 'ku_main',
            name: 'Amphitheatre',
            category: LandmarkCategory.recreation,
            description: 'Outdoor venue for performances and student gatherings.',
            latitude: -1.1810,
            longitude: 36.9315,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'ku_food_1',
            campusId: 'ku_main',
            name: 'Eastern Zone Mess',
            category: LandmarkCategory.food,
            description: 'Dining facility serving the eastern part of the campus.',
            latitude: -1.1830,
            longitude: 36.9330,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
        ];

      case 'strath_main':
        return [
          Landmark(
            id: 'strath_gate_1',
            campusId: 'strath_main',
            name: 'Main Gate',
            category: LandmarkCategory.transport,
            description: 'Main entrance located along Ole Sangale Road.',
            latitude: -1.3098,
            longitude: 36.8126,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'strath_stc_1',
            campusId: 'strath_main',
            name: 'Student Centre',
            category: LandmarkCategory.food,
            description: 'Hub for student activities and dining options.',
            latitude: -1.3105,
            longitude: 36.8130,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'strath_lib_1',
            campusId: 'strath_main',
            name: 'Library',
            category: LandmarkCategory.academic,
            description: 'Modern library facilities for Strathmore students.',
            latitude: -1.3090,
            longitude: 36.8120,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'strath_academic_2',
            campusId: 'strath_main',
            name: 'Phase I',
            category: LandmarkCategory.academic,
            description: 'Original campus buildings housing classrooms and faculty offices.',
            latitude: -1.3095,
            longitude: 36.8125,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'strath_academic_3',
            campusId: 'strath_main',
            name: 'Phase III (SBS)',
            category: LandmarkCategory.academic,
            description: 'Strathmore Business School building.',
            latitude: -1.3115,
            longitude: 36.8135,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
        ];

      case 'jkuat_main':
        return [
          Landmark(
            id: 'jkuat_admin_1',
            campusId: 'jkuat_main',
            name: 'Admin Block',
            category: LandmarkCategory.administration,
            description: 'Central administrative offices of Jomo Kenyatta University.',
            latitude: -1.1026,
            longitude: 37.0135,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'jkuat_gate_1',
            campusId: 'jkuat_main',
            name: 'Main Gate',
            category: LandmarkCategory.transport,
            description: 'The primary entrance to the Juja campus.',
            latitude: -1.1050,
            longitude: 37.0150,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'jkuat_food_1',
            campusId: 'jkuat_main',
            name: 'Hall 6 Mess',
            category: LandmarkCategory.food,
            description: 'Popular student cafeteria for JKUAT students.',
            latitude: -1.1010,
            longitude: 37.0120,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'jkuat_lib_1',
            campusId: 'jkuat_main',
            name: 'Main Library',
            category: LandmarkCategory.academic,
            description: 'Central library and information resource centre.',
            latitude: -1.1035,
            longitude: 37.0145,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: 'jkuat_academic_2',
            campusId: 'jkuat_main',
            name: 'Science Complex',
            category: LandmarkCategory.academic,
            description: 'Facility housing various science laboratories and lecture halls.',
            latitude: -1.1020,
            longitude: 37.0125,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
        ];

      default:
        // Return a few generic landmarks for any campus that doesn't have a specific mock entry
        return [
          Landmark(
            id: '${campusId}_gate_gen',
            campusId: campusId,
            name: 'Campus Main Gate',
            category: LandmarkCategory.transport,
            description: 'The primary entrance to the campus.',
            latitude: -1.2801, // These coordinates should ideally be derived from campus.latitude
            longitude: 36.8163,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
          Landmark(
            id: '${campusId}_admin_gen',
            campusId: campusId,
            name: 'Administration Block',
            category: LandmarkCategory.administration,
            description: 'The central administrative building.',
            latitude: -1.2805,
            longitude: 36.8168,
            isAccessible: true,
            createdAt: now,
            updatedAt: now,
          ),
        ];
    }
  }
}
